raw_stimuli = [
    {
      "SceneImage": "class6.jpg",
      "consist_obj": "Textbook",
      "Basic": "Classroom",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Living Room",
      "probe": "Coffee Maker"
    },
    {
      "SceneImage": "bathroom7.jpg",
      "consist_obj": "Soap Bar",
      "Basic": "Bathroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Classroom",
      "probe": "Backpack"
    },
    {
      "SceneImage": "child_bedroom.png",
      "consist_obj": "Teddy Bear",
      "Basic": "Bedroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Bedroom",
      "probe": "Teddy Bear"
    },
    {
      "SceneImage": "fruit_bowl.jpg",
      "consist_obj": "Blender",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Living Room",
      "probe": "Floor Lamp"
    },
    {
      "SceneImage": "Nature14.jpg",
      "consist_obj": "Wild Berries",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Fire Hydrant"
    },
    {
      "SceneImage": "dining3.jpg",
      "consist_obj": "Plate",
      "Basic": "Dining Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Bathroom",
      "probe": "Toilet Paper"
    },
    {
      "SceneImage": "urbanstreet19.jpg",
      "consist_obj": "Subway Station Sign",
      "Basic": "Urban Street",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Birdhouse"
    },
    {
      "SceneImage": "highway6.jpg",
      "consist_obj": "Speed Limit Sign",
      "Basic": "Highway",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Highway",
      "probe": "Speed Limit Sign"
    },
    {
      "SceneImage": "coast7.jpg",
      "consist_obj": "Beach Towel",
      "Basic": "Coast",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Open Country",
      "probe": "Fence"
    },
    {
      "SceneImage": "modern_livingroom.png",
      "consist_obj": "Floor Lamp",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Baking Tray"
    },
    {
      "SceneImage": "citycenter10.jpg",
      "consist_obj": "Souvenir Stand",
      "Basic": "City Center",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "City Center",
      "probe": "Souvenir Stand"
    },
    {
      "SceneImage": "corridor3.jpg",
      "consist_obj": "Fire Extinguisher",
      "Basic": "Corridor",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Classroom",
      "probe": "Notebook"
    },
    {
      "SceneImage": "farm7.jpg",
      "consist_obj": "Tractor",
      "Basic": "Farm",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Farm",
      "probe": "Tractor"
    },
    {
      "SceneImage": "bedroom12.jpg",
      "consist_obj": "Dresser",
      "Basic": "Bedroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Bedroom",
      "probe": "Dresser"
    },
    {
      "SceneImage": "play2.jpg",
      "consist_obj": "Swing Set",
      "Basic": "Playground",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Open Country",
      "probe": "Farmhouse"
    },
    {
      "SceneImage": "coast11.jpg",
      "consist_obj": "Lifeguard Tower",
      "Basic": "Coast",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Coast",
      "probe": "Lifeguard Tower"
    },
    {
      "SceneImage": "living16.jpg",
      "consist_obj": "Television",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Living Room",
      "probe": "Television"
    },
    {
      "SceneImage": "highway9.jpg",
      "consist_obj": "Road Work Sign",
      "Basic": "Highway",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Bird Bath"
    },
    {
      "SceneImage": "blender.jpg",
      "consist_obj": "Pan",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Classroom",
      "probe": "Textbook"
    },
    {
      "SceneImage": "Urban14.jpg",
      "consist_obj": "Parking Meter",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Playground",
      "probe": "Seesaw"
    },
    {
      "SceneImage": "tan_kitchen.png",
      "consist_obj": "Knife",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Conference Room",
      "probe": "Briefcase"
    },
    {
      "SceneImage": "Nature36.jpg",
      "consist_obj": "Lily Pad",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "City Center",
      "probe": "Flag Pole"
    },
    {
      "SceneImage": "farm4.jpg",
      "consist_obj": "Feeding Trough",
      "Basic": "Farm",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Urban Street",
      "probe": "Subway Station Sign"
    },
    {
      "SceneImage": "living6.jpg",
      "consist_obj": "Vase",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Office",
      "probe": "Sticky Notes"
    },
    {
      "SceneImage": "suburb3.jpg",
      "consist_obj": "Mailbox",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Fishing Rod"
    },
    {
      "SceneImage": "kitchen10.jpg",
      "consist_obj": "Rolling Pin",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Kitchen",
      "probe": "Rolling Pin"
    },
    {
      "SceneImage": "bedroom11.jpg",
      "consist_obj": "Nightstand",
      "Basic": "Bedroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Bedroom",
      "probe": "Nightstand"
    },
    {
      "SceneImage": "forest2.jpg",
      "consist_obj": "Bird Nest",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Forest",
      "probe": "Bird Nest"
    },
    {
      "SceneImage": "dining7.jpg",
      "consist_obj": "Spoon",
      "Basic": "Dining Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Bedroom",
      "probe": "Comforter Blanket"
    },
    {
      "SceneImage": "class8.jpg",
      "consist_obj": "Pencil Case",
      "Basic": "Classroom",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Classroom",
      "probe": "Pencil Case"
    },
    {
      "SceneImage": "urbanstreet12.jpg",
      "consist_obj": "Telephone Booth",
      "Basic": "Urban Street",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Urban Street",
      "probe": "Telephone Booth"
    },
    {
      "SceneImage": "class9.jpg",
      "consist_obj": "Crayons",
      "Basic": "Classroom",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Classroom",
      "probe": "Crayons"
    },
    {
      "SceneImage": "opencountry8.jpg",
      "consist_obj": "Radio Tower",
      "Basic": "Open Country",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Coast",
      "probe": "Beach Towel"
    },
    {
      "SceneImage": "coast8.jpg",
      "consist_obj": "Lighthouse",
      "Basic": "Coast",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Playground",
      "probe": "Picnic Table"
    },
    {
      "SceneImage": "bathroom3.jpg",
      "consist_obj": "Toilet Paper",
      "Basic": "Bathroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Conference Room",
      "probe": "Laptop"
    },
    {
      "SceneImage": "highway8.jpg",
      "consist_obj": "Yield Sign",
      "Basic": "Highway",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Highway",
      "probe": "Yield Sign"
    },
    {
      "SceneImage": "forest11.jpg",
      "consist_obj": "Log Cabin",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Forest",
      "probe": "Log Cabin"
    },
    {
      "SceneImage": "bedroom5.jpg",
      "consist_obj": "Alarm Clock",
      "Basic": "Bedroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Corridor",
      "probe": "Fire Extinguisher"
    },
    {
      "SceneImage": "opencountry2.jpg",
      "consist_obj": "Farmhouse",
      "Basic": "Open Country",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Kayak"
    },
    {
      "SceneImage": "natural_fall.png",
      "consist_obj": "Fishing Rod",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Lawn Mower"
    },
    {
      "SceneImage": "urbanstreet30.jpg",
      "consist_obj": "Bus Stop Shelter",
      "Basic": "Urban Street",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Urban Street",
      "probe": "Bus Stop Shelter"
    },
    {
      "SceneImage": "highway10.jpg",
      "consist_obj": "Billboard",
      "Basic": "Highway",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Highway",
      "probe": "Billboard"
    },
    {
      "SceneImage": "suburb4.jpg",
      "consist_obj": "Crosswalk",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Suburban",
      "probe": "Crosswalk"
    },
    {
      "SceneImage": "flowers.jpg",
      "consist_obj": "Picture Frame",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Living Room",
      "probe": "Picture Frame"
    },
    {
      "SceneImage": "play5.jpg",
      "consist_obj": "Soccer Ball",
      "Basic": "Playground",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Playground",
      "probe": "Soccer Ball"
    },
    {
      "SceneImage": "conference7.jpg",
      "consist_obj": "Projector",
      "Basic": "Conference Room",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Oven Mitts"
    },
    {
      "SceneImage": "Urban10.jpg",
      "consist_obj": "Bicycle",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Suburban",
      "probe": "Bicycle"
    },
    {
      "SceneImage": "office9.jpg",
      "consist_obj": "Paper Shredder",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Office",
      "probe": "Paper Shredder"
    },
    {
      "SceneImage": "clock.jpg",
      "consist_obj": "Stop Sign",
      "Basic": "Urban Street",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Urban Street",
      "probe": "Stop Sign"
    },
    {
      "SceneImage": "office4.jpg",
      "consist_obj": "Tape Dispenser",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Knife"
    },
    {
      "SceneImage": "citycenter12.jpg",
      "consist_obj": "Historic Plaque",
      "Basic": "City Center",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Toadstool Mushroom"
    },
    {
      "SceneImage": "bin.jpg",
      "consist_obj": "Rocking Chair",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Bathroom",
      "probe": "Soap Bar"
    },
    {
      "SceneImage": "play12.jpg",
      "consist_obj": "Seesaw",
      "Basic": "Playground",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Open Country",
      "probe": "Radio Tower"
    },
    {
      "SceneImage": "suburb1.jpg",
      "consist_obj": "Lawn Mower",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Farm",
      "probe": "Scarecrow"
    },
    {
      "SceneImage": "kitchen16.jpg",
      "consist_obj": "Oven Mitts",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Living Room",
      "probe": "TV Remote"
    },
    {
      "SceneImage": "farm3.jpg",
      "consist_obj": "Scarecrow",
      "Basic": "Farm",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "City Center",
      "probe": "Historic Plaque"
    },
    {
      "SceneImage": "corridor2.jpg",
      "consist_obj": "Bathroom Sign",
      "Basic": "Corridor",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Living Room",
      "probe": "Vase"
    },
    {
      "SceneImage": "bedroom13.jpg",
      "consist_obj": "Laundry Hamper",
      "Basic": "Bedroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Bedroom",
      "probe": "Laundry Hamper"
    },
    {
      "SceneImage": "citycenter11.jpg",
      "consist_obj": "Horse Carriage",
      "Basic": "City Center",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "City Center",
      "probe": "Horse Carriage"
    },
    {
      "SceneImage": "pond.png",
      "consist_obj": "Birdhouse",
      "Basic": "Suburban",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Highway",
      "probe": "Road Work Sign"
    },
    {
      "SceneImage": "bedroom14.jpg",
      "consist_obj": "Comforter Blanket",
      "Basic": "Bedroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Conference Room",
      "probe": "Projector"
    },
    {
      "SceneImage": "MDS201.jpg",
      "consist_obj": "Rock",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Forest",
      "probe": "Rock"
    },
    {
      "SceneImage": "corridor1.jpg",
      "consist_obj": "Drinking Fountain",
      "Basic": "Corridor",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Corridor",
      "probe": "Drinking Fountain"
    },
    {
      "SceneImage": "class3.jpg",
      "consist_obj": "Notebook",
      "Basic": "Classroom",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Living Room",
      "probe": "Rocking Chair"
    },
    {
      "SceneImage": "fire_hydrant.jpg",
      "consist_obj": "Flag Pole",
      "Basic": "City Center",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Farm",
      "probe": "Feeding Trough"
    },
    {
      "SceneImage": "Urban_Image_08.jpg",
      "consist_obj": "Traffic Light",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Suburban",
      "probe": "Traffic Light"
    },
    {
      "SceneImage": "bust.jpg",
      "consist_obj": "TV Remote",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Apron"
    },
    {
      "SceneImage": "suburb6.jpg",
      "consist_obj": "Utility Pole",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Camping Tent"
    },
    {
      "SceneImage": "play3.jpg",
      "consist_obj": "Sandbox",
      "Basic": "Playground",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Playground",
      "probe": "Sandbox"
    },
    {
      "SceneImage": "conference8.jpg",
      "consist_obj": "Projector Screen",
      "Basic": "Conference Room",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Conference Room",
      "probe": "Projector Screen"
    },
    {
      "SceneImage": "kitchen15.jpg",
      "consist_obj": "Apron",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Office",
      "probe": "Tape Dispenser"
    },
    {
      "SceneImage": "brick_apartment.png",
      "consist_obj": "Bird Bath",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Coast",
      "probe": "Lighthouse"
    },
    {
      "SceneImage": "office8.jpg",
      "consist_obj": "Sticky Notes",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Stand Mixer"
    },
    {
      "SceneImage": "farm2.jpg",
      "consist_obj": "Wheelbarrow",
      "Basic": "Farm",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Farm",
      "probe": "Wheelbarrow"
    },
    {
      "SceneImage": "conference1.jpg",
      "consist_obj": "Briefcase",
      "Basic": "Conference Room",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Bedroom",
      "probe": "Alarm Clock"
    },
    {
      "SceneImage": "bathroom2.jpg",
      "consist_obj": "Shower Head",
      "Basic": "Bathroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Bathroom",
      "probe": "Shower Head"
    },
    {
      "SceneImage": "elephant.jpg",
      "consist_obj": "Napkin",
      "Basic": "Dining Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Dining Room",
      "probe": "Napkin"
    },
    {
      "SceneImage": "urbanstreet1.jpg",
      "consist_obj": "Newspaper Box",
      "Basic": "Urban Street",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Urban Street",
      "probe": "Newspaper Box"
    },
    {
      "SceneImage": "Nature40.jpg",
      "consist_obj": "Kayak",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Utility Pole"
    },
    {
      "SceneImage": "kitchen17.jpg",
      "consist_obj": "Baking Tray",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Corridor",
      "probe": "Exit Sign"
    },
    {
      "SceneImage": "forest1.jpg",
      "consist_obj": "Toadstool Mushroom",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Urban Street",
      "probe": "Crosswalk Signal"
    },
    {
      "SceneImage": "opencountry5.jpg",
      "consist_obj": "Pitchfork",
      "Basic": "Open Country",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Open Country",
      "probe": "Pitchfork"
    },
    {
      "SceneImage": "bathroom6.jpg",
      "consist_obj": "Plunger",
      "Basic": "Bathroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Bathroom",
      "probe": "Plunger"
    },
    {
      "SceneImage": "office10.jpg",
      "consist_obj": "Stapler",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Office",
      "probe": "Stapler"
    },
    {
      "SceneImage": "class11.jpg",
      "consist_obj": "Backpack",
      "Basic": "Classroom",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Dining Room",
      "probe": "Spoon"
    },
    {
      "SceneImage": "corridor5.jpg",
      "consist_obj": "Fire Alarm",
      "Basic": "Corridor",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Corridor",
      "probe": "Fire Alarm"
    },
    {
      "SceneImage": "plant_bathroom.png",
      "consist_obj": "Slippers",
      "Basic": "Bathroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Bathroom",
      "probe": "Slippers"
    },
    {
      "SceneImage": "living17.jpg",
      "consist_obj": "Armchair Recliner",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Living Room",
      "probe": "Armchair Recliner"
    },
    {
      "SceneImage": "farm1.jpg",
      "consist_obj": "Hay Bale",
      "Basic": "Farm",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Farm",
      "probe": "Hay Bale"
    },
    {
      "SceneImage": "forest9.jpg",
      "consist_obj": "Axe",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Forest",
      "probe": "Axe"
    },
    {
      "SceneImage": "Nature47.jpg",
      "consist_obj": "Fishing Boat",
      "Basic": "Coast",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Coast",
      "probe": "Fishing Boat"
    },
    {
      "SceneImage": "conference3.jpg",
      "consist_obj": "Phone Set",
      "Basic": "Conference Room",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Conference Room",
      "probe": "Phone Set"
    },
    {
      "SceneImage": "basketball_net.jpg",
      "consist_obj": "Bench",
      "Basic": "Playground",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Playground",
      "probe": "Bench"
    },
    {
      "SceneImage": "urbanstreet28.jpg",
      "consist_obj": "Crosswalk Signal",
      "Basic": "Urban Street",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Wild Berries"
    },
    {
      "SceneImage": "fan.jpg",
      "consist_obj": "Calculator",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Office",
      "probe": "Calculator"
    },
    {
      "SceneImage": "kitchen13.jpg",
      "consist_obj": "Stand Mixer",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Living Room",
      "probe": "DVD Player"
    },
    {
      "SceneImage": "dining8.jpg",
      "consist_obj": "Fork",
      "Basic": "Dining Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Dining Room",
      "probe": "Fork"
    },
    {
      "SceneImage": "bathroom4.jpg",
      "consist_obj": "Razor",
      "Basic": "Bathroom",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Bathroom",
      "probe": "Razor"
    },
    {
      "SceneImage": "dining5.jpg",
      "consist_obj": "Bowl",
      "Basic": "Dining Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Dining Room",
      "probe": "Bowl"
    },
    {
      "SceneImage": "coast10.jpg",
      "consist_obj": "Surfboard",
      "Basic": "Coast",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Coast",
      "probe": "Surfboard"
    },
    {
      "SceneImage": "living13.jpg",
      "consist_obj": "DVD Player",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Pan"
    },
    {
      "SceneImage": "forest14.jpg",
      "consist_obj": "Camping Tent",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Highway",
      "probe": "Motorcycle"
    },
    {
      "SceneImage": "glass.jpg",
      "consist_obj": "Toaster",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Kitchen",
      "probe": "Toaster"
    },
    {
      "SceneImage": "suburb2.jpg",
      "consist_obj": "Fire Hydrant",
      "Basic": "Suburban",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Playground",
      "probe": "Swing Set"
    },
    {
      "SceneImage": "opencountry1.jpg",
      "consist_obj": "Fence",
      "Basic": "Open Country",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Parking Meter"
    },
    {
      "SceneImage": "coast3.jpg",
      "consist_obj": "Buoy",
      "Basic": "Coast",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Coast",
      "probe": "Buoy"
    },
    {
      "SceneImage": "citycenter2.jpg",
      "consist_obj": "Taxi",
      "Basic": "City Center",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "City Center",
      "probe": "Taxi"
    },
    {
      "SceneImage": "Nature22.jpg",
      "consist_obj": "Wildflower",
      "Basic": "Forest",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Suburban",
      "probe": "Mailbox"
    },
    {
      "SceneImage": "play10.jpg",
      "consist_obj": "Picnic Table",
      "Basic": "Playground",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Lily Pad"
    },
    {
      "SceneImage": "office1.jpg",
      "consist_obj": "Pencil Holder",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Office",
      "probe": "Pencil Holder"
    },
    {
      "SceneImage": "bell.jpg",
      "consist_obj": "Coffee Maker",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "Yes",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Corridor",
      "probe": "Bathroom Sign"
    },
    {
      "SceneImage": "dining6.jpg",
      "consist_obj": "Tablecloth",
      "Basic": "Dining Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Consistent",
      "probe_cat": "Dining Room",
      "probe": "Tablecloth"
    },
    {
      "SceneImage": "conference5.jpg",
      "consist_obj": "Laptop",
      "Basic": "Conference Room",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Inconsistent",
      "probe_cat": "Kitchen",
      "probe": "Blender"
    },
    {
      "SceneImage": "living9.jpg",
      "consist_obj": "Ottoman",
      "Basic": "Living Room",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Living Room",
      "probe": "Ottoman"
    },
    {
      "SceneImage": "highway12.jpg",
      "consist_obj": "Motorcycle",
      "Basic": "Highway",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og2",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Inconsistent",
      "probe_cat": "Forest",
      "probe": "Wildflower"
    },
    {
      "SceneImage": "briefcase.jpg",
      "consist_obj": "Printer",
      "Basic": "Office",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "Yes",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Office",
      "probe": "Printer"
    },
    {
      "SceneImage": "citycenter26.jpg",
      "consist_obj": "Statue",
      "Basic": "City Center",
      "Superordinate": "Human",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "Yes",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "City Center",
      "probe": "Statue"
    },
    {
      "SceneImage": "opencountry3.jpg",
      "consist_obj": "Windmill",
      "Basic": "Open Country",
      "Superordinate": "Natural",
      "InOut": "Outdoors",
      "group_labels": "og1",
      "Inverted": "No",
      "Duration": 150,
      "Consistent": "Consistent",
      "probe_cat": "Open Country",
      "probe": "Windmill"
    },
    {
      "SceneImage": "wood_kitchen.png",
      "consist_obj": "Broom",
      "Basic": "Kitchen",
      "Superordinate": "Private",
      "InOut": "Indoors",
      "group_labels": "ig1",
      "Inverted": "No",
      "Duration": 400,
      "Consistent": "Consistent",
      "probe_cat": "Kitchen",
      "probe": "Broom"
    },
    {
      "SceneImage": "corridor4.jpg",
      "consist_obj": "Exit Sign",
      "Basic": "Corridor",
      "Superordinate": "Public",
      "InOut": "Indoors",
      "group_labels": "ig2",
      "Inverted": "No",
      "Duration": 250,
      "Consistent": "Inconsistent",
      "probe_cat": "Dining Room",
      "probe": "Plate"
    }
  ]